### ISSUE TITLE
My thoughts on what the daemon should be written in and how it should work.

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#12]
I know this might be a hot take, and I have deeply considered this, but I believe that the daemon should be written in [GoLang](https://golang.org/)...  Now there is a reason that I am thinking about going with Go for the daemon, and I'll explain it to you, but first I want to explain how the daemon is going to work.

So, the way that this platform is going to work is that you login to your dashboard, create an instance of whatever you're trying to create weather it be a node app, apache server, minecraft server etc. and that request will be routed to our backend server along with all of the options associated with it.  Based upon these options, the backend server will look at a list of all of the daemons and determine which daemon will be used to host it.  Once this has been determined, it will be marked in whatever storage medium we are using to store instance data.  Now, when you go to start an instance, a request will be sent to the daemon which will tell it to spin up an instance of whatever application has been requested, now this is where I get to the part of why I want to do this in go.

These instances that get spun up, I want them to be docker containers.  The reason I want them to be docker containers is that from my experience, it is very easy to manage docker containers as well as have many of them on one machine.  Something that I want to note is that Docker is written in Go, therefore Go will most likely be a more stable and reliable Language to go with for the most support possible.  Go has also proven to be a very fast and efficient language in many different facets such as API management and performance.

Now, I am not just considering one language, I am also considering using Rust as a daemon language.  From my research, Rust seems to be just as fast, if not faster than Go, and has fewer trade-offs in terms of run-time speed.  This is very good for us when you consider the fact that these daemons at peak hours could be spinning up many containers per minute.  This would also provide a much cleaner and a much more universal programming environment that has a cleaner Syntax.

Both Rust and Go have their benefits and drawbacks, but I think that they are both very good candidates for the language used in the writing of the daemon.  I would love to hear your opinions and ideas as to what language you think the daemon should be written in.   Please feel free to comment these ideas.

- Holo

**Comment by willdoescode** [comment]
I think both are good, rust is much faster but docker is written in go. It probably comes down to which you are more comfortable developing in.

**Comment by samarmohan** [comment]
Yeah, which one do you know best? I personally like Rust more but doing both would be the best.

**Comment by nadirabbas** [comment]
I learnt Elixir on DogeHouse, now, I don't know Rust or Go, but I do want to learn Rust, so I say go with Rust lol.

**Comment by ghost** [comment]
I see everyone using Rust now, instead of GoLang.. I think it would be better to go with the new cool thing

**Comment by lucemans** [comment]
https://pterodactyl.io/ 👀

**Comment by HoloPanio** [comment]
> https://pterodactyl.io/ 👀

I was wondering how long it would be before somebody tried to compare us to pterodactyl lmao.  We will not use it nor are we copying it.  We have two completely different niches.

**Comment by TheOtterlord** [comment]
and also, it uses php

**Comment by lucemans** [comment]
Pterodactyl uses containers in the background.. 😄
Golang daemon... 🤣 
And yeah, a php laravel frontend, but thats hypothetically interchangable.
Im just messing around tho xD Do ur thing

**Comment by HoloPanio** [comment]
> Pterodactyl uses containers in the background.. 
> Golang daemon... 
> And yeah, a php laravel frontend, but thats hypothetically interchangable.
> Im just messing around tho xD Do ur thing

Well we're going to be using rust as our daemon, but yeah, we are completely different from pterodactyl.
