### ISSUE TITLE
Auto deploy broken

### ISSUE THREAD

**Issue by amitojsingh366** [HoloPanio/duxcore#15]
**Describe the bug**
The auto deploy system is broken

**To Reproduce**
1. Go to the repo
2. make a commit
3. Notice how the website isn't updated with your commit

**Expected behavior**
Website updates

**Screenshots**
![image](https://user-images.githubusercontent.com/35400192/122334385-540f1d80-cf42-11eb-8ccc-42c784fe8358.png)
![image](https://user-images.githubusercontent.com/35400192/122334446-6be6a180-cf42-11eb-9306-c0b88da635d8.png)

**Device (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox dev
 - Version: 90.0b8

**Additional context**
i've been telling @HoloPanio this exact thing for the past 2 weeks but somehow something happens and we aren't talking about it anymore, this has gone too far and i think this topic is cursed or something. i don't mean to leak private convos or anything but this has happened so many times that im just tired of it so below are some examples:

![image](https://user-images.githubusercontent.com/35400192/122334705-cd0e7500-cf42-11eb-9489-74b053432fc8.png)
![image](https://user-images.githubusercontent.com/35400192/122334786-e9aaad00-cf42-11eb-9a38-c31174b69dec.png)
![image](https://user-images.githubusercontent.com/35400192/122334917-22e31d00-cf43-11eb-8521-6c5c471002c7.png)
![image](https://user-images.githubusercontent.com/35400192/122335042-558d1580-cf43-11eb-96ef-f63c018fdc81.png)

**Comment by amitojsingh366** [comment]
someone please notice this issue before i go insane

**Comment by he1d1** [comment]
Did you try refreshing or clearing your cache

**Comment by amitojsingh366** [comment]
> 
> 
> Did you try refreshing or clearing your cache

yeah i did, it's not a caching issue. auto deploy is broken

**Comment by he1d1** [comment]
I can't reproduce this because im not a contributor

**Comment by HoloPanio** [comment]
Fixed and redeployed.
