### ISSUE TITLE
Website gives a 502 error

### ISSUE THREAD

**Issue by EwanFox** [HoloPanio/duxcore#31]
I get a 502 error upon going to the website: https://duxcore.co/
![image](https://user-images.githubusercontent.com/60858870/128198003-815ebba3-3660-418a-8548-7172ac91a6a5.png)

**Comment by HoloPanio** [comment]
This is a known issue, should be resolved soon

**Comment by HoloPanio** [comment]
So it is soon, and it is not resolved.  We take great pride and care of our servers here at Duxcore, but unfortunately the boogey man broke into our data centre and implode our web servers with black magic.  Truly a devastating event, but our team has been working incredibly hard to bring these servers back to life.  Hopefully I'll have another update for you in the future.

---
Jackson R.
Contributor and Magic Defender of Duxcore (not)inc.

**Comment by HoloPanio** [comment]
I'm glad to report that this issue has been resolved.  Thank you for letting us know! You can now visit our temporary website [here](https://duxcore.co)

---
Jackson R.
Project Manager and Lead Backend Developer
