### ISSUE TITLE
We need a navbar

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#36]
I am currently very busy working on the backend of Duxcore, and I would like to get the navbar of the new dashboard done.  If you can design and have some time to help, we would love your help setting up a navbar for our dashboard.

https://github.com/duxcore/duxcore/tree/overhaul/dashboard

**Comment by he1d1** [comment]
The Material You [navigation rail](https://m3.material.io/components/navigation-rail/overview) could work

**Comment by HoloPanio** [comment]
> The Material You [navigation rail](https://m3.material.io/components/navigation-rail/overview) could work

I'm not so sure about that, it isn't exactly the style we're trying to go for

**Comment by HoloPanio** [comment]
also we are not really going for a side nav at the moment.

**Comment by HoloPanio** [comment]
Working on getting something else setup
