### ISSUE TITLE
Continuing work on daemon & service integration 

### ISSUE THREAD

**Issue by HoloPanio** [HoloPanio/duxcore#94]
### BUGS
- [x] [ CORE ] New authorizationStore middleware for WEBSOCKT ROUTES ONLY will not allow ws api route to work at all, it gets stuck on the step where it creates the variable from the header.
- [x] [ CORE/MANIFESTATION ] Web socket middleware hardly works, please look into it and see if it is something that can be resolved on our end, or if it is an issue with the `express-ws` library itself.
- [x] [ DAEMON ] When attempting to attach self to container, daemon returns the following error message and doesn't send anything to the ws client.
![image](https://user-images.githubusercontent.com/30759238/206636186-60e20d19-71f1-499f-86ce-7d8cc4f07c0e.png)

**Comment by overlisting** [comment]
Regarding the daemon attach bug: You're not following the exact schema that's in the docs. Change the `data` field to an object like in the deno example: https://github.com/duxcore/duxcore/blob/4ade05ca0add8f16ffb26f3a716088193f9a5f84/daemon/docs/attach-example.js#L20-L23

(you currently have this:)
https://github.com/duxcore/duxcore/blob/4ade05ca0add8f16ffb26f3a716088193f9a5f84/core/src/classes/DaemonServerManager.ts#L48

**Comment by HoloPanio** [comment]
removed some items to move to individual issues.
